In [1]:
import os, sys
sys.path.append(os.path.join(os.getcwd(), "../"))
import eigenSolverNN as esnn
import numpy as np
import tensorflow as tf
import warnings
import Eigenvects as ev

Try the algorythm with orthagonal initial condiotion

In [2]:
A = np.load('A.npy')
A = tf.convert_to_tensor(A)

In [ ]:
eigenvectors, eigenvalues = ev.findEigenvectors(A)
print(eigenvalues)
#prints the true eigenvalues
A = A.numpy()
[E, V] = np.linalg.eigh(A)
print(E)

Finds some points that aren't eigenvectors of A but still has low cost. Try to force search until it finds all eigenvalues instead.

In [3]:
eigenvectors, eigenvalues = ev.Search_Until_Find(A)
print(eigenvalues)
A = A.numpy()
#prints the true eigenvalues
[E, V] = np.linalg.eigh(A)
print(E)

### FINDING EIGENVECTOR NR.0 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x00000223578A9B10>, <keras.layers.core.dense.Dense object at 0x00000223578A9720>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-0.32318782 -0.0292165  -0.62624758 -0.2821335   1.2604693  -0.66849856]


 Training model with SGD using 4 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████| 50000/50000 [14:22<00:00, 57.96it/s]
C:\Users\breit\Desktop\Atom\FYS-STK\Project\FYS-STK4155-Project-3\Eigenvects.py:49: UserWarning: eigenvector ([[-0.08224674  0.10581586 -0.07809353 -0.20182097 -0.32255485 -0.09678008]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.18761498428709633, last: 0.18761498428709633
[[0.87228364]
 [0.9591128 ]
 [0.7388812 ]
 [0.99178884]
 [1.05062167]
 [0.7845387 ]]
Found something not an eigenvector of A: 
 [[-0.08224674  0.10581586 -0.07809353 -0.20182097 -0.32255485 -0.09678008]]
### FINDING EIGENVECTOR NR.0 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002235790D840>, <keras.layers.core.dense.Dense object at 0x000002237F06EAD0>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [ 0.56780179  0.45154301  0.10427437 -0.36695212 -0.52540878 -1.28980776]


 Training model with SGD using 4 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████| 50000/50000 [12:29<00:00, 66.69it/s]


losses were: initial 0.0012873719127241352, last: 0.0012873719127241352
[[1.06662477]
 [0.99044417]
 [0.98341189]
 [1.00126849]
 [1.00250225]
 [0.94342079]]
Found new eigenvector: 
 [[-0.1046819   0.1727829  -0.07834208 -0.35314607 -0.55151372 -0.14936678]] 
 eigenvalue [[-2.30595902]]
### FINDING EIGENVECTOR NR.1 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x00000223577E7940>, <keras.layers.core.dense.Dense object at 0x0000022357889C60>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-0.79812381  0.46346732 -0.64288786  0.50251024  0.25973266 -0.71443011]


 Training model with SGD using 4 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████| 50000/50000 [09:09<00:00, 91.04it/s]


losses were: initial 4.717797654168871e-05, last: 4.717797654168871e-05
[[1.0229733 ]
 [1.01940085]
 [0.9825221 ]
 [0.99720345]
 [0.98135605]
 [0.98136714]]
Found new eigenvector: 
 [[ 0.11137297 -0.38341325 -0.22473185 -0.26349817  0.13719395 -0.30286995]] 
 eigenvalue [[2.20038953]]
### FINDING EIGENVECTOR NR.2 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002235790D7E0>, <keras.layers.core.dense.Dense object at 0x000002237F06DC90>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-0.25528191  0.51421227  0.67796058 -1.0335905   0.77448958  0.00217207]


 Training model with SGD using 4 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████| 50000/50000 [08:46<00:00, 94.94it/s]


losses were: initial 4.0516143040957025e-05, last: 4.0516143040957025e-05
[[0.99833751]
 [1.19090415]
 [0.83131847]
 [1.0533757 ]
 [0.98120565]
 [1.01822593]]
Found new eigenvector: 
 [[ 0.07310062 -0.09114937  0.09645567  0.19775667  0.33990694  0.06466422]] 
 eigenvalue [[-2.29170592]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x00000223577E7FA0>, <keras.layers.core.dense.Dense object at 0x000002237F01BB50>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-0.15429848 -0.69307072  0.32514946  0.93232724 -0.68430431 -0.54172611]


 Training model with SGD using 4 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████| 50000/50000 [10:03<00:00, 82.89it/s]
C:\Users\breit\Desktop\Atom\FYS-STK\Project\FYS-STK4155-Project-3\Eigenvects.py:49: UserWarning: eigenvector ([[-0.61268593 -0.04349576 -0.12522608  0.34441161  0.00735753 -0.38367943]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.00013024388283938227, last: 0.00013024388283938227
[[1.01551217]
 [0.82881661]
 [0.94539567]
 [0.96477977]
 [3.18217304]
 [0.99603826]]
Found something not an eigenvector of A: 
 [[-0.61268593 -0.04349576 -0.12522608  0.34441161  0.00735753 -0.38367943]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002237F678880>, <keras.layers.core.dense.Dense object at 0x000002237F48BCD0>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-0.39523299 -0.46583809  0.29011504  0.10862094 -0.19430624  0.04659779]


 Training model with SGD using 4 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████| 50000/50000 [09:14<00:00, 90.20it/s]
C:\Users\breit\Desktop\Atom\FYS-STK\Project\FYS-STK4155-Project-3\Eigenvects.py:49: UserWarning: eigenvector ([[-0.06958018  0.09399607 -0.0384501  -0.19540352 -0.3158601  -0.07509738]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.00027841515114845856, last: 0.00027841515114845856
[[0.9021798 ]
 [0.99695306]
 [1.24706551]
 [1.04431317]
 [0.97744154]
 [1.12303282]]
Found something not an eigenvector of A: 
 [[-0.06958018  0.09399607 -0.0384501  -0.19540352 -0.3158601  -0.07509738]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002237F6198A0>, <keras.layers.core.dense.Dense object at 0x000002237F49F760>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-0.43222073 -0.35016601  0.1960399   0.2868414  -0.18634827 -0.19508001]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [08:00<00:00, 104.08it/s]


losses were: initial 4.347968061100909e-05, last: 4.347968061100909e-05
[[0.99075195]
 [1.08217571]
 [1.13682752]
 [1.01863587]
 [0.98704496]
 [0.96357292]]
Duplicate [[-2.30469286]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002230CF53CA0>, <keras.layers.core.dense.Dense object at 0x000002237F6580D0>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-2.78688551 -0.24315112  0.18719615  0.29249109  0.48067004 -0.89263113]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [08:08<00:00, 102.45it/s]


losses were: initial 0.001171332676323363, last: 0.001171332676323363
[[0.99634363]
 [0.99814379]
 [1.00467876]
 [1.00200629]
 [0.99918662]
 [1.00340022]]
Duplicate [[-2.30656141]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002237F59A980>, <keras.layers.core.dense.Dense object at 0x000002230CF53790>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-2.70466964 -3.1845197   2.42829333 -2.84635488 -0.01051487  3.70658037]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [07:34<00:00, 110.11it/s]
C:\Users\breit\Desktop\Atom\FYS-STK\Project\FYS-STK4155-Project-3\Eigenvects.py:49: UserWarning: eigenvector ([[-1.96579315 -0.14452561 -0.40752607  1.07503136  0.02698371 -1.20655255]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.25623611199831114, last: 0.25623611199831114
[[1.00306264]
 [0.78165535]
 [0.96990301]
 [1.00970658]
 [0.5554838 ]
 [0.99095317]]
Found something not an eigenvector of A: 
 [[-1.96579315 -0.14452561 -0.40752607  1.07503136  0.02698371 -1.20655255]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002237F069150>, <keras.layers.core.dense.Dense object at 0x000002230CF969B0>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-0.13020854 -2.80926407  1.66766549  0.85776635 -1.82998516  0.69583341]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [07:42<00:00, 108.16it/s]


losses were: initial 0.0039328718748501525, last: 0.0039328718748501525
[[0.98870147]
 [0.99955411]
 [1.00353274]
 [1.00501414]
 [0.98355321]
 [0.99996962]]
Duplicate [[2.20198]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002230CF94880>, <keras.layers.core.dense.Dense object at 0x000002230CFDD990>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-4.22001277 -2.57352186  2.25764574 -4.26837655  1.24084463  4.30649487]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [07:50<00:00, 106.18it/s]


losses were: initial 0.4479705847391358, last: 0.4479705847391358
[[1.01477117]
 [1.0001428 ]
 [0.99616187]
 [1.00106398]
 [1.00623081]
 [0.99771534]]
Duplicate [[2.20198562]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002237F406B00>, <keras.layers.core.dense.Dense object at 0x000002230D0A35B0>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [ 2.78498421 -2.11136003  0.97106286  2.33595246 -2.74296621 -0.29838204]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [08:02<00:00, 103.64it/s]
C:\Users\breit\Desktop\Atom\FYS-STK\Project\FYS-STK4155-Project-3\Eigenvects.py:49: UserWarning: eigenvector ([[ 0.09084897 -0.12965374  0.02505338  0.303083    0.45080794  0.13172611]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.007453883800458333, last: 0.007453883800458333
[[0.99870315]
 [1.12207792]
 [1.60354475]
 [0.97229266]
 [1.00305671]
 [0.97139795]]
Found something not an eigenvector of A: 
 [[ 0.09084897 -0.12965374  0.02505338  0.303083    0.45080794  0.13172611]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002230D01FA90>, <keras.layers.core.dense.Dense object at 0x000002230D0BC190>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [  1.24532802  -0.04471553   1.39615238 -11.28645703   3.794589
  11.01672826]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [07:55<00:00, 105.18it/s]


losses were: initial 10.768866362300693, last: 10.768866362300693
[[0.94947737]
 [0.99241462]
 [1.00688128]
 [0.95260363]
 [1.01195673]
 [1.06044996]]
Duplicate [[2.19947311]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002237F48AB00>, <keras.layers.core.dense.Dense object at 0x000002230CF12470>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [ -5.00795265   3.58945361  -0.7236865  -11.39404722   7.45804497
   7.44263348]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [08:02<00:00, 103.71it/s]
C:\Users\breit\Desktop\Atom\FYS-STK\Project\FYS-STK4155-Project-3\Eigenvects.py:49: UserWarning: eigenvector ([[ 0.03892685  0.5338196   0.3956603   0.84529804 -0.47993157  0.20806699]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.05524631316208668, last: 0.05524631316208668
[[-1.39306218]
 [ 0.99891428]
 [ 1.05642622]
 [ 0.85196755]
 [ 1.08329023]
 [ 2.88698449]]
Found something not an eigenvector of A: 
 [[ 0.03892685  0.5338196   0.3956603   0.84529804 -0.47993157  0.20806699]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002230D18FD00>, <keras.layers.core.dense.Dense object at 0x000002230D16D960>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [ 3.25978351 -7.96027055  5.40697332 -3.8034581  -3.83784696  8.83442115]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [07:54<00:00, 105.35it/s]
C:\Users\breit\Desktop\Atom\FYS-STK\Project\FYS-STK4155-Project-3\Eigenvects.py:49: UserWarning: eigenvector ([[ 0.79185943 -0.02489154 -0.31661159  0.01571809  0.53122533 -0.68805657]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.6766135339491364, last: 0.6766135339491364
[[   0.17882512]
 [  40.41178136]
 [   4.95531366]
 [-113.82439842]
 [  -0.8654419 ]
 [   2.37043972]]
Found something not an eigenvector of A: 
 [[ 0.79185943 -0.02489154 -0.31661159  0.01571809  0.53122533 -0.68805657]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002230D0A2440>, <keras.layers.core.dense.Dense object at 0x000002230CFDD4E0>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [-2.5735626   4.92534524 -3.18084855  1.13829685  2.96474899 -4.46866204]


 Training model with SGD using 4 batches and 50000 epochs.


100%|███████████████████████████████████████████████████████████████████████████| 50000/50000 [07:52<00:00, 105.77it/s]
C:\Users\breit\Desktop\Atom\FYS-STK\Project\FYS-STK4155-Project-3\Eigenvects.py:49: UserWarning: eigenvector ([[-0.01558639  0.10456879 -0.02718701 -0.34186416 -0.49685742  0.02828477]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.028082362567702232, last: 0.028082362567702232
[[ 4.5982789 ]
 [ 1.49302195]
 [ 3.91999086]
 [ 1.06246656]
 [ 0.95321994]
 [-4.21918221]]
Found something not an eigenvector of A: 
 [[-0.01558639  0.10456879 -0.02718701 -0.34186416 -0.49685742  0.02828477]]
### FINDING EIGENVECTOR NR.3 ###

------ Current settings of model: ------

Model:
Layers:
[<keras.layers.core.dense.Dense object at 0x000002230D125660>, <keras.layers.core.dense.Dense object at 0x000002230CF53DF0>]
Number of neurons in hidden layer: 100
Optimizer: Adam
Learning rate: <tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.001>
Time grid has shape (100, 1) and goes from [0.] to [1.]
Starting from initial condition: [ 3.50938065 -0.74626042 -0.29033242  5.42264871 -3.31073886 -3.76679209]


 Training model with SGD using 4 batches and 50000 epochs.


  3%|█▉                                                                           | 1281/50000 [00:13<08:21, 97.20it/s]


IndexError: list index out of range

Finds three of them, but seem to fail to find all the others