### Searching for eigenvectors using a neural network
This notebook contains a very long cell output, which summarizes the search of eigenvectors using our neural network. Sometimes the network finds a new eigenvector, other times the gradient descent goes towards the zero vector and needs to be interrupted. 
To run this notebook simply run the call to `ev.Search_Until_Find` and wait for the network to be trained. Once a model is trained different things can happen:

1. A new eigenvector is found and it is therefore stored together with the trained model.

2. An eigenvector is found but it's multiple of another previously found, so it is discarded.

3. A vector $v$ which is not an eigenvector is found. This is considered to be the case when the elementwise division $ x_i = (Av)_i/v_i $ is assessed, and at least one value of $x_i$ differs by $x_0$ by more than $10\%$. In this case, the user is asked whether to continue the training or to just start with a new model.

In [1]:
import os, sys
sys.path.append(os.path.join(os.getcwd(), "../"))
import eigenSolverNN as esnn
import numpy as np
import tensorflow as tf
import warnings
import Eigenvects as ev

In [2]:
A = np.load('../A.npy')
A = tf.convert_to_tensor(A)

In [3]:
eigenvectors, eigenvalues, solvers = ev.Search_Until_Find(A, Nattempts=30)

### FINDING EIGENVECTOR NR. 0 ###

attempt number 1.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:39<00:00, 502.28it/s]


losses were: initial 6.988504578902842, last: 0.18627181872619472
For a perfect eigenvector, the following should be all 1.000
[[1.00411561]
 [1.00163301]
 [0.97771642]
 [0.99946719]
 [1.00115463]
 [0.9888993 ]]
Found new eigenvector: 
 [[-0.20607068  0.31475266 -0.16093815 -0.65322574 -1.02421859 -0.25876062]] 
 eigenvalue [[-2.30653569]]
### FINDING EIGENVECTOR NR. 1 ###

attempt number 2.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:37<00:00, 514.50it/s]


losses were: initial 9.850976021994038, last: 0.1518480924512555
For a perfect eigenvector, the following should be all 1.000
[[0.99141429]
 [1.00551381]
 [0.99546856]
 [0.99807977]
 [1.00124272]
 [0.99204503]]
Duplicate [[-2.30654918]]
### FINDING EIGENVECTOR NR. 1 ###

attempt number 3.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:40<00:00, 497.85it/s]


losses were: initial 201.5776124844819, last: 15.82489488319254
For a perfect eigenvector, the following should be all 1.000
[[0.99713475]
 [1.00024708]
 [1.00065778]
 [1.00052169]
 [0.99968267]
 [0.99933975]]
Found new eigenvector: 
 [[-0.83798894  2.82540136  1.52003514  1.75208929 -0.83798888  2.0808348 ]] 
 eigenvalue [[2.20200437]]
### FINDING EIGENVECTOR NR. 2 ###

attempt number 4.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:41<00:00, 493.96it/s]


losses were: initial 50.942967352383164, last: 1.8231632876421744
For a perfect eigenvector, the following should be all 1.000
[[1.00194873]
 [1.00321995]
 [1.00515367]
 [1.0011859 ]
 [0.99925535]
 [0.99635543]]
Duplicate [[-2.30655892]]
### FINDING EIGENVECTOR NR. 2 ###

attempt number 5.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:39<00:00, 503.47it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[0.06045649 0.18452951 0.0513631  0.0625474  0.02358325 0.01218203]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 16.780215548658013, last: 0.17114639084511762
For a perfect eigenvector, the following should be all 1.000
[[-1.43170474]
 [ 1.28576954]
 [ 0.58684388]
 [ 1.148765  ]
 [-2.08748189]
 [10.31400548]]
Found something not an eigenvector of A: 
 [[0.06045649 0.18452951 0.0513631  0.0625474  0.02358325 0.01218203]]
Approximate eigenvalue is [1.20171636].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 2 ###

attempt number 6.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:38<00:00, 506.31it/s]


losses were: initial 7.599443906610889, last: 0.15314437800100594
For a perfect eigenvector, the following should be all 1.000
[[0.9458893 ]
 [1.02247458]
 [1.05788706]
 [0.99592299]
 [0.99883914]
 [1.03445519]]
Duplicate [[-2.30612693]]
### FINDING EIGENVECTOR NR. 2 ###

attempt number 7.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:36<00:00, 519.66it/s]


losses were: initial 85.7734336028685, last: 0.15916149603526747
For a perfect eigenvector, the following should be all 1.000
[[1.01988616]
 [0.99918828]
 [0.99242345]
 [0.99665792]
 [1.02800154]
 [1.00047711]]
Duplicate [[2.20192715]]
### FINDING EIGENVECTOR NR. 2 ###

attempt number 8.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:40<00:00, 495.08it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[ 0.0611282  -0.32968459 -0.0184792   0.06606377 -0.0516172  -0.10404293]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 62.28916490011667, last: 1.7134008265496583
For a perfect eigenvector, the following should be all 1.000
[[ 1.98086749]
 [ 0.94111245]
 [ 4.64495568]
 [-0.62102229]
 [ 2.80073959]
 [ 1.34806724]]
Found something not an eigenvector of A: 
 [[ 0.0611282  -0.32968459 -0.0184792   0.06606377 -0.0516172  -0.10404293]]
Approximate eigenvalue is [1.74086353].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 2 ###

attempt number 9.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:43<00:00, 481.61it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.35951391 -0.07280769  0.0046406   0.20701343  0.05644232 -0.23085133]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 34.767555487490725, last: 0.3425312964405829
For a perfect eigenvector, the following should be all 1.000
[[ 0.82685518]
 [ 0.26890567]
 [30.17433744]
 [ 1.37585815]
 [ 4.04198871]
 [ 0.9967731 ]]
Found something not an eigenvector of A: 
 [[-0.35951391 -0.07280769  0.0046406   0.20701343  0.05644232 -0.23085133]]
Approximate eigenvalue is [-0.5861281].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 2 ###

attempt number 10.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:37<00:00, 511.15it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[ 0.07185566 -0.12052662  0.03228389  0.24506733  0.37645512  0.10550336]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 1.678247235960124, last: 0.025125769920366334
For a perfect eigenvector, the following should be all 1.000
[[1.03031802]
 [0.94546348]
 [1.32726712]
 [1.0053608 ]
 [0.99974373]
 [1.00080498]]
Found something not an eigenvector of A: 
 [[ 0.07185566 -0.12052662  0.03228389  0.24506733  0.37645512  0.10550336]]
Approximate eigenvalue is [-2.30362295].
Do you want to keep training the same model?[y/n]


 nù


### FINDING EIGENVECTOR NR. 2 ###

attempt number 11.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:39<00:00, 501.21it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.03772881 -0.0103849  -0.92159072  0.13765375 -0.11583336  0.52046402]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 3.8786413309855137, last: 0.004421247538540952
For a perfect eigenvector, the following should be all 1.000
[[1.15220814]
 [1.58311287]
 [1.00691341]
 [0.93709742]
 [1.09879619]
 [0.97679815]]
Found something not an eigenvector of A: 
 [[-0.03772881 -0.0103849  -0.92159072  0.13765375 -0.11583336  0.52046402]]
Approximate eigenvalue is [-1.54296629].
Do you want to keep training the same model?[y/n]


 y


### FINDING EIGENVECTOR NR. 2 ###

attempt number 11.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:34<00:00, 526.97it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.04052292 -0.01334363 -0.93533052  0.14544165 -0.11151553  0.52653548]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.004421236976001815, last: 0.0042224824380777855
For a perfect eigenvector, the following should be all 1.000
[[1.08782997]
 [1.3764376 ]
 [1.00506497]
 [0.94682812]
 [1.07895424]
 [0.98377073]]
Found something not an eigenvector of A: 
 [[-0.04052292 -0.01334363 -0.93533052  0.14544165 -0.11151553  0.52653548]]
Approximate eigenvalue is [-1.54279641].
Do you want to keep training the same model?[y/n]


 y


### FINDING EIGENVECTOR NR. 2 ###

attempt number 11.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:40<00:00, 498.09it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.04146208 -0.01723095 -0.96063348  0.1547388  -0.10687762  0.54198823]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.0042224809183765265, last: 0.0041829378411330255
For a perfect eigenvector, the following should be all 1.000
[[1.05718141]
 [1.23469961]
 [1.0037279 ]
 [0.96690319]
 [1.05058158]
 [0.98844782]]
Found something not an eigenvector of A: 
 [[-0.04146208 -0.01723095 -0.96063348  0.1547388  -0.10687762  0.54198823]]
Approximate eigenvalue is [-1.54259044].
Do you want to keep training the same model?[y/n]


 y


### FINDING EIGENVECTOR NR. 2 ###

attempt number 11.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:38<00:00, 507.30it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.04159878 -0.01823381 -0.96682252  0.15697523 -0.10544061  0.54576205]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.004182937040131531, last: 0.0041696011086326465
For a perfect eigenvector, the following should be all 1.000
[[1.05014626]
 [1.20864966]
 [1.0032296 ]
 [0.97372988]
 [1.0447103 ]
 [0.98984492]]
Found something not an eigenvector of A: 
 [[-0.04159878 -0.01823381 -0.96682252  0.15697523 -0.10544061  0.54576205]]
Approximate eigenvalue is [-1.54255402].
Do you want to keep training the same model?[y/n]


 Y


### FINDING EIGENVECTOR NR. 2 ###

attempt number 11.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:36<00:00, 516.63it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.04100123 -0.01804789 -0.96959475  0.15749174 -0.10550773  0.54740333]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.004169600883347441, last: 0.004162163816770817
For a perfect eigenvector, the following should be all 1.000
[[1.06351443]
 [1.23414952]
 [1.00314203]
 [0.97402552]
 [1.04395911]
 [0.99004842]]
Found something not an eigenvector of A: 
 [[-0.04100123 -0.01804789 -0.96959475  0.15749174 -0.10550773  0.54740333]]
Approximate eigenvalue is [-1.54254331].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 2 ###

attempt number 12.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:43<00:00, 484.12it/s]


losses were: initial 82.55317128951737, last: 4.051899442919599
For a perfect eigenvector, the following should be all 1.000
[[0.99760746]
 [1.04366268]
 [1.0021264 ]
 [0.99859511]
 [1.09825934]
 [1.00666056]]
Found new eigenvector: 
 [[-2.98110885 -0.20852196 -0.61323654  1.6382576   0.04335981 -1.82361518]] 
 eigenvalue [[-0.53955159]]
### FINDING EIGENVECTOR NR. 3 ###

attempt number 13.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:39<00:00, 500.17it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.04524413  0.10064957 -0.03076234 -0.22042922 -0.35433782 -0.10252496]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 8.34759621236695, last: 0.026245077952075056
For a perfect eigenvector, the following should be all 1.000
[[1.59884092]
 [1.17297145]
 [1.20772121]
 [1.05236278]
 [0.96319794]
 [0.89551887]]
Found something not an eigenvector of A: 
 [[-0.04524413  0.10064957 -0.03076234 -0.22042922 -0.35433782 -0.10252496]]
Approximate eigenvalue is [-2.29278315].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 3 ###

attempt number 14.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:40<00:00, 499.95it/s]


losses were: initial 24.85978039472774, last: 0.1046501635677007
For a perfect eigenvector, the following should be all 1.000
[[1.02151444]
 [0.99951789]
 [1.00199695]
 [0.99550256]
 [1.00889622]
 [0.99828615]]
Duplicate [[2.20196059]]
### FINDING EIGENVECTOR NR. 3 ###

attempt number 15.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:41<00:00, 494.99it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.34467001 -0.01455682 -0.08702666  0.21882309  0.00937763 -0.22208951]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 4.787132434294863, last: 0.04609535133941244
For a perfect eigenvector, the following should be all 1.000
[[1.03630588]
 [3.52325861]
 [1.22991207]
 [0.94253519]
 [6.00380094]
 [0.91327886]]
Found something not an eigenvector of A: 
 [[-0.34467001 -0.01455682 -0.08702666  0.21882309  0.00937763 -0.22208951]]
Approximate eigenvalue is [-0.53852477].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 3 ###

attempt number 16.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:40<00:00, 498.53it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[ 0.0740448  -0.15643631  0.16065779  0.38024711 -0.39615264  0.11568677]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 21.27849597088085, last: 0.7461821739693345
For a perfect eigenvector, the following should be all 1.000
[[1.43640229]
 [0.72478873]
 [1.24066932]
 [1.09780735]
 [0.86758093]
 [1.3564266 ]]
Found something not an eigenvector of A: 
 [[ 0.0740448  -0.15643631  0.16065779  0.38024711 -0.39615264  0.11568677]]
Approximate eigenvalue is [1.74003062].
Do you want to keep training the same model?[y/n]


 Y


### FINDING EIGENVECTOR NR. 3 ###

attempt number 16.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:36<00:00, 519.57it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[ 0.04145862 -0.06100023  0.11836357  0.24537311 -0.24912588  0.09568324]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.7461821934419623, last: 0.7455576234627195
For a perfect eigenvector, the following should be all 1.000
[[1.17401572]
 [0.44052361]
 [1.14540308]
 [1.10567577]
 [0.85323019]
 [1.27221369]]
Found something not an eigenvector of A: 
 [[ 0.04145862 -0.06100023  0.11836357  0.24537311 -0.24912588  0.09568324]]
Approximate eigenvalue is [1.79232814].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 3 ###

attempt number 17.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:29<00:00, 557.83it/s]


losses were: initial 111.44463053505775, last: 3.9960529912074603
For a perfect eigenvector, the following should be all 1.000
[[1.00145675]
 [0.99608866]
 [0.99580218]
 [1.00140968]
 [0.99944499]
 [1.00635632]]
Duplicate [[-2.30655297]]
### FINDING EIGENVECTOR NR. 3 ###

attempt number 18.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:30<00:00, 551.51it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[ 0.02735027 -0.27907674 -0.12449388 -0.09616155 -0.01396835 -0.1604282 ]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 13.411394383806401, last: 0.6254648518452637
For a perfect eigenvector, the following should be all 1.000
[[ 3.81288162]
 [ 1.02053246]
 [ 0.76143319]
 [ 1.02478616]
 [-4.2588503 ]
 [ 1.03073666]]
Found something not an eigenvector of A: 
 [[ 0.02735027 -0.27907674 -0.12449388 -0.09616155 -0.01396835 -0.1604282 ]]
Approximate eigenvalue is [2.04897901].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 3 ###

attempt number 19.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:35<00:00, 525.99it/s]


losses were: initial 21.22991677843947, last: 0.6935591381347505
For a perfect eigenvector, the following should be all 1.000
[[0.97820338]
 [1.00848585]
 [0.9504198 ]
 [0.9846692 ]
 [1.00893315]
 [0.98275487]]
Duplicate [[-2.30630423]]
### FINDING EIGENVECTOR NR. 3 ###

attempt number 20.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:38<00:00, 506.74it/s]


losses were: initial 12.321083943375847, last: 0.2878850029014472
For a perfect eigenvector, the following should be all 1.000
[[0.95964529]
 [1.04831295]
 [1.03718563]
 [0.99245278]
 [1.00402393]
 [0.94826376]]
Duplicate [[-2.30554423]]
### FINDING EIGENVECTOR NR. 3 ###

attempt number 21.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:35<00:00, 524.37it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.09051645  0.16885269 -0.05270716 -0.35887755 -0.57581818 -0.12709641]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 347.66081597498174, last: 8.991702401474816
For a perfect eigenvector, the following should be all 1.000
[[1.2071378 ]
 [1.02872297]
 [1.51988176]
 [1.05538725]
 [0.95673719]
 [1.20123798]]
Found something not an eigenvector of A: 
 [[-0.09051645  0.16885269 -0.05270716 -0.35887755 -0.57581818 -0.12709641]]
Approximate eigenvalue is [-2.29741399].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 3 ###

attempt number 22.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:42<00:00, 487.59it/s]


losses were: initial 15.025663684592852, last: 0.09287011008782327
For a perfect eigenvector, the following should be all 1.000
[[1.00046994]
 [1.01951111]
 [1.00647971]
 [0.9995525 ]
 [0.99826392]
 [0.99943855]]
Duplicate [[-2.30652766]]
### FINDING EIGENVECTOR NR. 3 ###

attempt number 23.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:40<00:00, 499.32it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[ 0.0602281  -0.11117293 -0.03740011  0.24064199  0.33686177  0.11704696]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 1.7001130354142566, last: 0.012726402229412483
For a perfect eigenvector, the following should be all 1.000
[[1.04161147]
 [0.92767284]
 [0.01013056]
 [0.98525434]
 [1.02082701]
 [1.04511781]]
Found something not an eigenvector of A: 
 [[ 0.0602281  -0.11117293 -0.03740011  0.24064199  0.33686177  0.11704696]]
Approximate eigenvalue is [-2.26721328].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 3 ###

attempt number 24.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:37<00:00, 511.13it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[ 0.02580411  0.03797039  0.15164047  0.07748862  0.09760578 -0.02036438]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 3.6886225030527733, last: 0.24932292059953273
For a perfect eigenvector, the following should be all 1.000
[[ 2.58189427]
 [-3.65935399]
 [ 0.83823848]
 [ 0.48120161]
 [ 2.15221705]
 [ 4.67022842]]
Found something not an eigenvector of A: 
 [[ 0.02580411  0.03797039  0.15164047  0.07748862  0.09760578 -0.02036438]]
Approximate eigenvalue is [-1.28152009].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 3 ###

attempt number 25.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:39<00:00, 502.79it/s]


losses were: initial 5.212489229833136, last: 0.2076039392294994
For a perfect eigenvector, the following should be all 1.000
[[1.00168451]
 [1.00137569]
 [1.00075386]
 [0.99701766]
 [0.99191363]
 [1.00039273]]
Duplicate [[2.20196398]]
### FINDING EIGENVECTOR NR. 3 ###

attempt number 26.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:37<00:00, 511.54it/s]


losses were: initial 435.75532364320924, last: 30.094088515549156
For a perfect eigenvector, the following should be all 1.000
[[1.00410882]
 [0.99989339]
 [0.99684301]
 [1.00005908]
 [1.00021486]
 [1.00116094]]
Duplicate [[2.20200179]]
### FINDING EIGENVECTOR NR. 3 ###

attempt number 27.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:39<00:00, 501.52it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-1.73221131 -1.60491145  0.90589005 -1.07918144 -0.02779649  1.721263  ]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 19.86516423599621, last: 0.14740944629706132
For a perfect eigenvector, the following should be all 1.000
[[0.98833501]
 [1.00318795]
 [1.00730288]
 [0.99882824]
 [0.51978374]
 [1.00760538]]
Found something not an eigenvector of A: 
 [[-1.73221131 -1.60491145  0.90589005 -1.07918144 -0.02779649  1.721263  ]]
Approximate eigenvalue is [0.19045173].
Do you want to keep training the same model?[y/n]


 y


### FINDING EIGENVECTOR NR. 3 ###

attempt number 27.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:43<00:00, 480.81it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-1.74671554 -1.6202541   0.91583176 -1.0913192  -0.02681537  1.74052162]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.147409173571203, last: 0.14064340927206098
For a perfect eigenvector, the following should be all 1.000
[[0.99756857]
 [0.99759112]
 [1.00173274]
 [1.00121971]
 [0.80028158]
 [1.0036244 ]]
Found something not an eigenvector of A: 
 [[-1.74671554 -1.6202541   0.91583176 -1.0913192  -0.02681537  1.74052162]]
Approximate eigenvalue is [0.19045421].
Do you want to keep training the same model?[y/n]


 y


### FINDING EIGENVECTOR NR. 3 ###

attempt number 27.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:35<00:00, 524.87it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-1.75211019 -1.62332519  0.91726686 -1.09279972 -0.02793507  1.74380672]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.14064333457907993, last: 0.1388877166375603
For a perfect eigenvector, the following should be all 1.000
[[0.99373031]
 [0.99681717]
 [1.01218557]
 [0.99508741]
 [0.5675254 ]
 [1.00775638]]
Found something not an eigenvector of A: 
 [[-1.75211019 -1.62332519  0.91726686 -1.09279972 -0.02793507  1.74380672]]
Approximate eigenvalue is [0.19045328].
Do you want to keep training the same model?[y/n]


 Y


### FINDING EIGENVECTOR NR. 3 ###

attempt number 27.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:43<00:00, 483.43it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-1.73540145 -1.60983479  0.91025722 -1.08125235 -0.02680134  1.72939474]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 0.13888769874951323, last: 0.13886147952350844
For a perfect eigenvector, the following should be all 1.000
[[0.99677122]
 [0.99326932]
 [1.00989662]
 [0.99978781]
 [1.76823093]
 [1.00624016]]
Found something not an eigenvector of A: 
 [[-1.73540145 -1.60983479  0.91025722 -1.08125235 -0.02680134  1.72939474]]
Approximate eigenvalue is [0.19045428].
Do you want to keep training the same model?[y/n]


 y


### FINDING EIGENVECTOR NR. 3 ###

attempt number 27.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:43<00:00, 484.60it/s]


losses were: initial 0.13870503467814604, last: 0.13774071819896505
For a perfect eigenvector, the following should be all 1.000
[[0.99976385]
 [1.00166183]
 [0.99668671]
 [1.00293972]
 [0.9515332 ]
 [0.99856834]]
Found new eigenvector: 
 [[-1.75248532 -1.62802468  0.91990039 -1.0967914  -0.02666975  1.74860544]] 
 eigenvalue [[0.19045446]]
### FINDING EIGENVECTOR NR. 4 ###

attempt number 28.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:41<00:00, 493.62it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.87954241 -0.04161613 -0.21063218  0.48969328 -0.00161565 -0.54219627]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 27.981863204036877, last: 0.735594739240758
For a perfect eigenvector, the following should be all 1.000
[[ 1.01617567]
 [ 1.76850138]
 [ 1.22110173]
 [ 0.9249368 ]
 [31.95598797]
 [ 0.98049352]]
Found something not an eigenvector of A: 
 [[-0.87954241 -0.04161613 -0.21063218  0.48969328 -0.00161565 -0.54219627]]
Approximate eigenvalue is [-0.54001035].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 4 ###

attempt number 29.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:39<00:00, 503.33it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[ 0.01626962  0.0736695  -0.08728352  0.12985839 -0.05026668 -0.12629885]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 1.4963002139781398, last: 0.040171036581857965
For a perfect eigenvector, the following should be all 1.000
[[474.05731657]
 [-13.67640628]
 [-76.60876525]
 [ 42.02564465]
 [  6.78065682]
 [ -9.07693236]]
Found something not an eigenvector of A: 
 [[ 0.01626962  0.0736695  -0.08728352  0.12985839 -0.05026668 -0.12629885]]
Approximate eigenvalue is [0.01160303].
Do you want to keep training the same model?[y/n]


 n


### FINDING EIGENVECTOR NR. 4 ###

attempt number 30.


 Training model with SGD using 1 batches and 50000 epochs.


100%|████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [01:41<00:00, 490.22it/s]
/media/gianmarco/Users/HOME/Desktop/università/Machine Learning/FYS-STK4155-Project-3/notebooks/../Eigenvects.py:51: UserWarning: eigenvector ([[-0.16737466 -0.27860489  0.17823839 -0.23363263  0.03209312  0.32474037]]) might not be an eigenvector of A.
  warnings.warn(f"eigenvector ({eigvec}) might not be an eigenvector of A.")


losses were: initial 7.625017467762967, last: 0.29449150983063227
For a perfect eigenvector, the following should be all 1.000
[[  4.74966446]
 [  1.91466882]
 [ -1.81211468]
 [  2.15379518]
 [-10.0566863 ]
 [ -0.31139106]]
Found something not an eigenvector of A: 
 [[-0.16737466 -0.27860489  0.17823839 -0.23363263  0.03209312  0.32474037]]
Approximate eigenvalue is [0.14065638].
Do you want to keep training the same model?[y/n]


 Y


In [ ]:
## FIRST OF ALL SAVE THE MODELS FOUND
import os
cwd = os.getcwd()
for ii in range(len(solvers)):
    solvers[ii].model.save(cwd+f"/model_{ii}")
    nptosave = solvers[ii].x0.numpy()
    np.save(cwd+f"/initial_condition_{ii}.npy", nptosave)

In [21]:
true_eigvals, true_eigvecs = np.linalg.eigh(A.numpy())

eigvalsNN = []
eigvecsNN = []
for solver in solvers:
    eigval, eigvec = solver.compute_eig()
    eigvalsNN.append(eigval.numpy()[0,0])
    eigvecsNN.append(eigvec.numpy()[0])

In [24]:
#right indices to choose the eigenvectors we found from the result of numpy.linalg.eigh
indices = np.array([0,5,2,3])

In [26]:
true_eigvals_cmp = true_eigvals[indices]
true_eigvecs_cmp = true_eigvecs[:,indices]

In [29]:
#save found eigenvectors and eigenvalues
np.save("eigenvaluesNN.npy", np.array(eigvalsNN))
for ii in range(4):
    np.save(f"eigenvecNN_{ii}.npy", np.array(eigvecsNN[ii]))

In [32]:
#print nice comparison in latex
def parallel_check(v,w):
    '''should return 1 if v and w are parallel'''
    num = np.dot(v,w)**2
    den = np.dot(v,v)*np.dot(w,w)
    
    return num/den


for ii in range(4):
    truelam = true_eigvals_cmp[ii]
    NNlam = eigvalsNN[ii]
    true_eig = true_eigvecs_cmp[:,ii]
    print(f"{truelam:.3f}", f"{NNlam:.3f}", f"{np.abs( (truelam-NNlam)/truelam ):.3e}", 
          f"{1-parallel_check(eigvecsNN[ii], true_eig):.3e}", sep=" & ", end=" \\\\\n")


-2.307 & -2.307 & 1.274e-05 & 1.904e-05 \\
2.202 & 2.202 & 5.757e-07 & 9.693e-07 \\
-0.540 & -0.540 & 3.231e-06 & 2.274e-06 \\
0.190 & 0.190 & 2.901e-07 & 3.070e-08 \\
